import doctor2 from "@/assets/dr-manu-gupta.jpeg";
import doctor3 from "@/assets/dr-agamya-saxena.jpeg";
import doctor4 from "@/assets/dr-kk-thakur.jpeg";

export const allDoctors = [
  {
    id: 1,
    name: "Dr. Manu Gupta",
    specialty: "Physician & Internal Medicine Specialist",
    department: "Internal Medicine",
    experience: "12+ Years",
    rating: 4.7,
    reviews: 210,
    education: "MBBS, MD (Internal Medicine)",
    image: doctor2,
    bio: "Dr. Manu Gupta is an experienced internal medicine specialist focusing on the diagnosis and management of adult medical conditions such as diabetes, hypertension, infections, and chronic lifestyle diseases. He emphasizes evidence-based treatment and long-term patient care.",
    achievements: [
      "Certified Internal Medicine Specialist",
      "Regular CME Participant",
      "Hospital Clinical Committee Member",
    ],
    languages: ["English", "Hindi"],
    availability: "Mon - Sat, 11 AM - 5 PM",
    consultationFee: "₹1,200",
    phone: "+91 98XXX XXXXX",
    specializations: [
      "Diabetes Management",
      "Hypertension",
      "Infectious Diseases",
      "Thyroid Disorders",
      "General Medicine",
    ],
  },
  {
    id: 2,
    name: "Dr. Agamya Saxena",
    specialty: "Vascular & Interventional Radiologist",
    department: "Radiology",
    experience: "10+ Years",
    rating: 4.8,
    reviews: 185,
    education:
      "MBBS, MD (Radiology), Fellowship in Vascular & Interventional Radiology",
    image: doctor3,
    bio: "Dr. Agamya Saxena specializes in minimally invasive, image-guided procedures for vascular and non-vascular conditions. His work includes angioplasties, embolization procedures, biopsies, and catheter-based interventions aimed at reducing the need for surgery.",
    achievements: [
      "Fellowship Trained in Interventional Radiology",
      "Contributor to Clinical Case Studies",
      "Advanced Imaging Certification",
    ],
    languages: ["English", "Hindi"],
    availability: "Mon - Fri, 10 AM - 4 PM",
    consultationFee: "₹1,800",
    phone: "+91 97XXX XXXXX",
    specializations: [
      "Peripheral Angioplasty",
      "Dialysis Access Interventions",
      "Image-Guided Biopsies",
      "Embolization Procedures",
      "Vascular Imaging",
    ],
  },
  {
    id: 3,
    name: "Dr. KK Thakur",
    specialty: "Anesthesiologist",
    department: "Anesthesiology",
    experience: "5+ Years",
    rating: 4.8,
    reviews: 198,
    education: "MBBS, MD (Anesthesiology)",
    image: doctor4,
    bio: "Dr. KK Thakur is an experienced anesthesiologist known for ensuring patient safety and comfort before, during, and after surgical procedures. He specializes in advanced anesthesia techniques and pain management.",
    achievements: [
      "Excellence in Anesthesia Care",
      "Patient Safety Award",
      "Senior Anesthesia Consultant",
    ],
    languages: ["English", "Hindi"],
    availability: "Mon - Sat, 9 AM - 6 PM",
    consultationFee: "₹1,200",
    phone: "+91 98XXX XXXXX",
    specializations: [
      "General Anesthesia",
      "Regional Anesthesia",
      "Pain Management",
      "Critical Care Support",
    ],
  },
];

export const allDepartments = [
  {
    id: 101,
    name: "Nephrology",
    shortDesc: "Specialized care for kidney diseases and disorders.",
    fullDesc:
      "The Nephrology department provides comprehensive diagnosis, treatment, and long-term management of kidney diseases, hypertension, chronic kidney disease, and renal failure.",
    image:
      "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=900&auto=format&fit=crop&q=60",
    features: [
      "Kidney Disease Management",
      "Chronic Kidney Care",
      "Hypertension Treatment",
    ],
    doctors: 4,
    experience: "15+ Years",
    timing: "9 AM - 6 PM",
    phone: "+91 123 456 7901",
    headDoctor: "Dr. Amit Verma",
    equipment: ["Renal Diagnostics", "Kidney Monitoring Systems"],
    category: "specialty",
  },
  {
    id: 102,
    name: "Dialysis Unit",
    shortDesc: "Hemodialysis services for patients with kidney failure.",
    fullDesc:
      "Our Dialysis Unit provides safe and effective hemodialysis treatment under the supervision of experienced nephrologists and trained dialysis technicians.",
    image:
      "https://images.unsplash.com/photo-1669930605340-801a0be1f5a3?w=900&auto=format&fit=crop&q=60",
    features: ["Hemodialysis", "Patient Monitoring", "Renal Support"],
    doctors: 3,
    experience: "15+ Years",
    timing: "24/7 Available",
    phone: "+91 123 456 7902",
    headDoctor: "Dr. Rajesh Sharma",
    equipment: ["Dialysis Machines", "RO Plant", "Patient Monitors"],
    category: "treatment",
  },
  {
    id: 103,
    name: "General Internal Medicine",
    shortDesc:
      "Comprehensive diagnosis and treatment of adult medical conditions.",
    fullDesc:
      "The General Internal Medicine department offers preventive care, diagnosis, and treatment for a wide range of adult illnesses with a patient-centered approach.",
    image:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=900&auto=format&fit=crop&q=60",
    features: [
      "General Consultation",
      "Chronic Disease Management",
      "Preventive Care",
    ],
    doctors: 5,
    experience: "18+ Years",
    timing: "9 AM - 7 PM",
    phone: "+91 123 456 7903",
    headDoctor: "Dr. Anil Kumar",
    equipment: ["ECG", "Patient Monitoring Systems"],
    category: "medicine",
  },
  {
    id: 104,
    name: "Cardiology",
    shortDesc: "Diagnosis and treatment of heart-related diseases.",
    fullDesc:
      "Our Cardiology department provides expert care for cardiovascular diseases including hypertension, heart failure, arrhythmias, and coronary artery disease.",
    image:
      "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=900&auto=format&fit=crop&q=60",
    features: ["ECG", "Heart Check-up", "Cardiac Consultation"],
    doctors: 4,
    experience: "20+ Years",
    timing: "9 AM - 6 PM",
    phone: "+91 123 456 7904",
    headDoctor: "Dr. Neha Kapoor",
    equipment: ["ECG Machine", "Cardiac Monitor", "Echo Machine"],
    category: "specialty",
  },
  {
    id: 105,
    name: "Urology",
    shortDesc: "Treatment for urinary tract and male reproductive disorders.",
    fullDesc:
      "The Urology department specializes in diagnosing and treating kidney stones, urinary tract disorders, prostate conditions, and other urological diseases.",
    image: "/anatomy-drawing-vintage-style.jpg",
    features: ["Kidney Stone Treatment", "Urological Surgery", "Urinary Care"],
    doctors: 4,
    experience: "18+ Years",
    timing: "9 AM - 6 PM",
    phone: "+91 123 456 7905",
    headDoctor: "Dr. Rohit Malhotra",
    equipment: ["Cystoscopy Unit", "Endoscopic Instruments"],
    category: "specialty",
  },
  {
    id: 106,
    name: "Plastic Surgery",
    shortDesc: "Reconstructive and cosmetic surgical procedures.",
    fullDesc:
      "Our Plastic Surgery department performs reconstructive and cosmetic procedures to restore function and improve appearance after injury, disease, or congenital conditions.",
    image:
      "https://images.unsplash.com/photo-1584515933487-779824d29309?w=900&auto=format&fit=crop&q=60",
    features: [
      "Reconstructive Surgery",
      "Cosmetic Procedures",
      "Scar Revision",
    ],
    doctors: 2,
    experience: "15+ Years",
    timing: "By Appointment",
    phone: "+91 123 456 7906",
    headDoctor: "Dr. Vivek Singh",
    equipment: ["Operation Theatre", "Microsurgical Instruments"],
    category: "surgery",
  },
  {
    id: 107,
    name: "General Surgery",
    shortDesc: "Surgical treatment for a wide range of medical conditions.",
    fullDesc:
      "The General Surgery department performs elective and emergency surgical procedures using modern surgical techniques.",
    image:
      "https://images.unsplash.com/photo-1551190822-a9333d879b1f?w=900&auto=format&fit=crop&q=60",
    features: ["Abdominal Surgery", "Minor Surgery", "Emergency Surgery"],
    doctors: 5,
    experience: "20+ Years",
    timing: "24/7 Emergency",
    phone: "+91 123 456 7907",
    headDoctor: "Dr. Sandeep Khanna",
    equipment: ["Operation Theatre", "Laparoscopic Instruments"],
    category: "surgery",
  },
  {
    id: 108,
    name: "Physiotherapy & Rehabilitation",
    shortDesc: "Physical therapy and rehabilitation services for recovery.",
    fullDesc:
      "The Physiotherapy & Rehabilitation department helps patients regain mobility, strength, and independence following injury, surgery, or illness.",
    image:
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&auto=format&fit=crop&q=60",
    features: ["Physical Therapy", "Rehabilitation", "Exercise Therapy"],
    doctors: 3,
    experience: "12+ Years",
    timing: "9 AM - 6 PM",
    phone: "+91 123 456 7908",
    headDoctor: "Dr. Priya Sharma",
    equipment: ["Exercise Equipment", "Electrotherapy Units"],
    category: "rehabilitation",
  },
  {
    id: 109,
    name: "Radiology",
    shortDesc: "Diagnostic imaging services for accurate diagnosis.",
    fullDesc:
      "Our Radiology department provides X-ray, ultrasound, and other imaging services to assist physicians in diagnosis and treatment planning.",
    image:
      "https://images.unsplash.com/photo-1581595219315-a187dd40c322?w=900&auto=format&fit=crop&q=60",
    features: ["Digital X-Ray", "Ultrasound", "Diagnostic Imaging"],
    doctors: 3,
    experience: "18+ Years",
    timing: "8 AM - 8 PM",
    phone: "+91 123 456 7909",
    headDoctor: "Dr. Meera Joshi",
    equipment: ["Digital X-Ray", "Ultrasound Machine"],
    category: "diagnostics",
  },
  {
    id: 110,
    name: "Pharmacy",
    shortDesc: "In-house pharmacy providing prescribed medicines.",
    fullDesc:
      "The Pharmacy ensures the availability of prescribed medicines and pharmaceutical guidance for both inpatients and outpatients.",
    image:
      "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=900&auto=format&fit=crop&q=60",
    features: [
      "Prescription Medicines",
      "Pharmaceutical Guidance",
      "Inpatient Supply",
    ],
    doctors: 0,
    experience: "10+ Years",
    timing: "24/7 Available",
    phone: "+91 123 456 7910",
    headDoctor: "Chief Pharmacist",
    equipment: ["Medicine Storage", "Inventory Management System"],
    category: "support",
  },
  {
    id: 111,
    name: "Laboratory",
    shortDesc: "Comprehensive diagnostic laboratory testing services.",
    fullDesc:
      "Our Laboratory performs routine and specialized diagnostic tests with accurate reporting to support patient diagnosis and treatment.",
    image:
      "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=900&auto=format&fit=crop&q=60",
    features: ["Blood Tests", "Biochemistry", "Pathology"],
    doctors: 2,
    experience: "15+ Years",
    timing: "24/7 Available",
    phone: "+91 123 456 7911",
    headDoctor: "Dr. Ritu Agarwal",
    equipment: ["Blood Analyzer", "Microscopes", "Biochemistry Analyzer"],
    category: "diagnostics",
  },
];
